name: physichronicles
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c1c1c1'
    - '#8a8a8a'
    - '#4f4f4f'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
