name: physichronicles
favicon: null
layout_spectrum: 0.5079
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#427ab5'
    - '#284473'
    - '#9d6a4f'
    - '#bfc4d4'
    - '#e09b71'
  brandStrength: 0.5524890036322176
  lightness: 0.5679508217144758
  saturation: 0.25
  rhythmicContrast: 0.9755567852407694
purpose: []
